// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1v6mnoeSnsRuwdG_2ISvrJnsO9dp9cLk',
    appId: '1:749906754952:web:ec9c9400992a742565ce3d',
    messagingSenderId: '749906754952',
    projectId: 'taskoo-c1feb',
    authDomain: 'taskoo-c1feb.firebaseapp.com',
    storageBucket: 'taskoo-c1feb.appspot.com',
    measurementId: 'G-HZP8Q40DZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1E2cN4qVJa6odP9mAxpF35TtqW3NugvY',
    appId: '1:749906754952:android:e2727419ec213d6165ce3d',
    messagingSenderId: '749906754952',
    projectId: 'taskoo-c1feb',
    storageBucket: 'taskoo-c1feb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjvDPTbbdxQAtifUXYggmfEk2ZFIZbZ2I',
    appId: '1:749906754952:ios:2d9fd6f7bbc0ab7365ce3d',
    messagingSenderId: '749906754952',
    projectId: 'taskoo-c1feb',
    storageBucket: 'taskoo-c1feb.appspot.com',
    iosClientId: '749906754952-mdm1vmcnfoqiie61g1k8e305gas7rajn.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjvDPTbbdxQAtifUXYggmfEk2ZFIZbZ2I',
    appId: '1:749906754952:ios:2d9fd6f7bbc0ab7365ce3d',
    messagingSenderId: '749906754952',
    projectId: 'taskoo-c1feb',
    storageBucket: 'taskoo-c1feb.appspot.com',
    iosClientId: '749906754952-mdm1vmcnfoqiie61g1k8e305gas7rajn.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskoo',
  );
}
